version: '3.8'

services: 
  mysqldb:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    expose:
      - "$MYSQL_DOCKER_PORT"
    ports:
      - "$MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT"
    volumes:
      - ./database_snapshots:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 5s
      retries: 3
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    environment:
      - DB_HOST=mysqldb
      - DB_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  database_snapshots: